[package]
name = "polygon-offsetting"
version = "0.1.9"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "polygon offsetting crate"
repository = "https://github.com/Akirami/polygon-offsetting"
readme = "README.md"
keywords = ["polygon", "offset", "geometry", "2d"]
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
